#!/bin/sh
if [ -n "$SKIP_METADATA_HOOK" ]; then
    exit 0
fi

commit_message=$(git log -1 --pretty=%B)

if [ -f .git/TRACKED_FILES ]; then
    while IFS= read -r file; do
        if [ -f "$file" ]; then
            sed -i "s/PENDING_COMMIT_MESSAGE/$commit_message/" "$file"
            export SKIP_METADATA_HOOK=1
            git add "$file"
            unset SKIP_METADATA_HOOK
        fi
    done < .git/TRACKED_FILES
    
    export SKIP_METADATA_HOOK=1
    git commit --amend --no-edit
    unset SKIP_METADATA_HOOK
    
    rm .git/TRACKED_FILES
fi

exit 0